version: '3.8'
services:
  database:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres-volume/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: devdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database:
    driver: local

